aaa

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -67,16 +67,16 @@ jobs:
       - name: Terraform Validate
         run: terraform validate
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color -lock-timeout=60m
-        # continue-on-error: true
+      # - name: Terraform Plan
+      # - id: plan
+      # - run: terraform plan -no-color -lock-timeout=60m
+      # continue-on-error: true
 
-        # - name: Terraform Plan Status
-        # - if: steps.plan.outcome == 'failure'
-        # - run: exit 1
+      # - name: Terraform Plan Status
+      # - if: steps.plan.outcome == 'failure'
+      # - run: exit 1
 
       - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.dryrun))
+        # if: github.ref == 'refs/heads/main' && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.dryrun))
         run: terraform apply -auto-approve -input=false
 
